# Generated by Django 6.0.2 on 2026-03-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_landingpagesetting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('Pengumuman', 'Pengumuman'), ('Kegiatan', 'Kegiatan'), ('Bansos', 'Bansos')], default='Pengumuman', max_length=50)),
                ('gambar_cover', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('konten', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='PejabatDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(1, 'Level 1 (Kades)'), (2, 'Level 2 (Sekdes)'), (3, 'Level 3 (Kaur/Kasi)'), (4, 'Level 4 (Kadus)')], default=3)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pejabat/')),
            ],
            options={
                'verbose_name_plural': 'Pejabat Desa',
                'ordering': ['level', 'id'],
            },
        ),
    ]
