# Generated by Django 6.0.2 on 2026-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usulanmusrenbang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='kewenangan',
            field=models.CharField(blank=True, choices=[('Desa', 'Desa'), ('Kabupaten', 'Kabupaten')], max_length=20, null=True),
        ),
    ]
