# Generated by Django 6.0.2 on 2026-03-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_programpembinaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalGotongRoyong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('lokasi', models.CharField(max_length=255)),
                ('koordinator', models.CharField(max_length=255)),
                ('alat_dibawa', models.TextField(help_text='Daftar alat yang perlu dibawa warga')),
                ('peserta_target', models.CharField(help_text='Misal: Warga RW 01, Pemuda Karang Taruna', max_length=255)),
                ('status', models.CharField(choices=[('Akan Datang', 'Akan Datang'), ('Berjalan', 'Berjalan'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Akan Datang', max_length=50)),
                ('penyelenggara_wilayah', models.CharField(help_text='Unit Detail LPM penyelenggara', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jadwal Gotong Royong',
                'ordering': ['tanggal', 'waktu'],
            },
        ),
    ]
