"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Using os.getenv with a fallback to prevent crash if ENV is missing on Vercel
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-only-for-initial-setup')

# Allow local and Vercel domains
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app,*').split(',')

# Disable APPEND_SLASH for Vercel stability
APPEND_SLASH = False


# CSRF Trusted Origins - auto-add Vercel domains
_raw_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_origins if o.strip()]
for host in ALLOWED_HOSTS:
    if host.strip() and not host.startswith(('localhost', '127.0.0.1')):
        CSRF_TRUSTED_ORIGINS.append(f"https://{host.strip().lstrip('.')}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'corsheaders',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',

    # Local apps
    'backend.users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security Settings for Production (aktif ketika DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend', 'dist'),
            os.path.join(BASE_DIR, 'staticfiles'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database Configuration
# Using dj-database-url to handle DATABASE_URL from environment variables (Supabase/Neon/etc)
# Fallback to local SQLite if DATABASE_URL is not set.
# 🚨 UNCONDITIONAL OVERRIDE: The user's Vercel environment variables are severely malformed
# (e.g., copied as "/postgres.yupa..." instead of "postgresql://postgres.yupa...").
# To guarantee successful login right now, we bypass the Vercel dashboard entirely.
db_url_env = 'postgresql://postgres.yupabeqtuqiajxgnvkup:Desacimanggu1_2007@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres'

try:
    DATABASES = {
        'default': dj_database_url.parse(
            db_url_env,
            conn_max_age=0,
            ssl_require=True
        )
    }
except Exception as e:
    # If it still fails, use dummy backend to allow boot, but fail on query
    print(f"DATABASE CONFIG ERROR: {str(e)}")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# GeoDjango Configuration (Disabled)
# To enable GIS, install OSGeo4W and uncomment relevant sections.


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add frontend/dist to STATICFILES_DIRS.
_frontend_dist = os.path.join(BASE_DIR, 'frontend', 'dist')
if DEBUG:
    STATICFILES_DIRS = [_frontend_dist] if os.path.exists(_frontend_dist) else []
else:
    # Always include in production as it will be built during deployment
    STATICFILES_DIRS = [_frontend_dist]

# WhiteNoise: serve frontend/dist files at root URL (for Vite assets)
WHITENOISE_ROOT = _frontend_dist
WHITENOISE_USE_FINDERS = True

# CORS Configuration
_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://localhost:3000',
        'https://desa-cimanggu-1.vercel.app',
    ]
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'False') == 'True'

# Alternatif spesifik origin:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# Supabase Storage Configuration
SUPABASE_URL = 'https://yupabeqtuqiajxgnvkup.supabase.co'
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cGFiZXF0dXFpYWp4Z252a3VwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjM4NzI4MywiZXhwIjoyMDkxOTYzMjgzfQ.CBvRd78y61TikljmlZZZPNSBWWSBGKLII9tjkMa9NDc')

# Modern Django Storage Configuration (Replaces DEFAULT_FILE_STORAGE)
STORAGES = {
    "default": {
        "BACKEND": "backend.users.storage.SupabaseStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (Public URL from Supabase)
MEDIA_URL = f"{SUPABASE_URL}/storage/v1/object/public/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
