# Generated by Django 6.0.2 on 2026-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesetting',
            name='carousel_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
        migrations.AddField(
            model_name='landingpagesetting',
            name='carousel_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
        migrations.AddField(
            model_name='landingpagesetting',
            name='carousel_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
