# Generated by Django 6.0.2 on 2026-03-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_landingpagesetting_carousel_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
