# Generated by Django 6.0.2 on 2026-03-08 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_berita_pejabatdesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pejabatdesa',
            name='id_unik',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('waktu_pulang', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir')], default='Hadir', max_length=20)),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='users.pejabatdesa')),
            ],
            options={
                'verbose_name_plural': 'Kehadiran',
                'ordering': ['-waktu_masuk'],
            },
        ),
    ]
