# Generated by Django 6.0.2 on 2026-03-08 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pejabatdesa_id_unik_kehadiran'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsulanMusrenbang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usulan_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('estimasi_biaya', models.DecimalField(decimal_places=2, max_digits=15)),
                ('foto_lapangan', models.ImageField(blank=True, null=True, upload_to='musrenbang/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Review'), ('DISETUJUI', 'Disetujui Kaur'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usulan_musrenbang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usulan Musrenbang',
                'ordering': ['-created_at'],
            },
        ),
    ]
