# Generated by Django 6.0.2 on 2026-03-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usulanmusrenbang'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='catatan_verifikator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
