# Generated by Django 6.0.2 on 2026-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usulanmusrenbang_catatan_verifikator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usulanmusrenbang',
            old_name='foto_lapangan',
            new_name='foto_1',
        ),
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='musrenbang/'),
        ),
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='musrenbang/'),
        ),
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='titik_koordinat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
