# Generated by Django 6.0.2 on 2026-03-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_foto_lapangan_usulanmusrenbang_foto_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaAnggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('FINAL', 'FINAL')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usulan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rab', to='users.usulanmusrenbang')),
            ],
            options={
                'verbose_name_plural': 'Rencana Anggaran (RAB)',
            },
        ),
        migrations.CreateModel(
            name='RencanaAnggaranItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('uraian', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('satuan', models.CharField(max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.rencanaanggaran')),
            ],
        ),
    ]
