# Generated by Django 6.0.2 on 2026-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rencanaanggaran_rencanaanggaranitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanaanggaran',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('FINAL', 'FINAL'), ('CAIR', 'CAIR')], default='DRAFT', max_length=20),
        ),
    ]
