# Generated by Django 6.0.2 on 2026-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_rencanaanggaran_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='progres_fisik',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usulanmusrenbang',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu Review'), ('DISETUJUI', 'Disetujui Kaur'), ('DITOLAK', 'Ditolak'), ('PELAKSANAAN', 'Pelaksanaan'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20),
        ),
    ]
