# Generated by Django 6.0.2 on 2026-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usulanmusrenbang_progres_fisik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usulanmusrenbang',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu Review'), ('DISETUJUI', 'Disetujui Kaur (RAB)'), ('DITOLAK', 'Ditolak'), ('MENUNGGU_PENCAIRAN', 'Menunggu Pencairan'), ('PELAKSANAAN', 'Pelaksanaan'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20),
        ),
    ]
