# Generated by Django 6.0.2 on 2026-03-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usulanmusrenbang_kewenangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenDED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dokumen', models.FileField(upload_to='dokumen_ded/')),
                ('nama_file', models.CharField(max_length=255)),
                ('ukuran_file', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_ded', to='users.usulanmusrenbang')),
            ],
        ),
    ]
