# Generated by Django 6.0.2 on 2026-03-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_dokumended'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenPerencanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('RPJMDes', 'RPJMDes'), ('RKPDes', 'RKPDes')], max_length=20)),
                ('judul', models.CharField(max_length=255)),
                ('periode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Drafting', 'Drafting'), ('Disahkan', 'Disahkan')], max_length=20)),
                ('file_dokumen', models.FileField(upload_to='dokumen_perencanaan/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
