# Generated by Django 6.0.2 on 2026-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_dokumenperencanaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirasiWarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_warga', models.CharField(max_length=255)),
                ('rt_rw', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Infrastruktur', 'Infrastruktur'), ('Sosial', 'Sosial'), ('Keamanan', 'Keamanan'), ('Layanan Publik', 'Layanan Publik')], max_length=100)),
                ('isi_pesan', models.TextField()),
                ('wilayah_tujuan', models.CharField(help_text="Unit Detail LPM, misal: '001'", max_length=255)),
                ('status', models.CharField(choices=[('Belum Dibaca', 'Belum Dibaca'), ('Ditindaklanjuti', 'Ditindaklanjuti'), ('Selesai', 'Selesai')], default='Belum Dibaca', max_length=50)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
