# Generated by Django 6.0.2 on 2026-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_aspirasiwarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPembinaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_program', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('sasaran', models.CharField(max_length=255)),
                ('tanggal_pelaksanaan', models.DateField()),
                ('jumlah_peserta', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Direncanakan', 'Direncanakan'), ('Berjalan', 'Berjalan'), ('Selesai', 'Selesai')], default='Direncanakan', max_length=50)),
                ('mentor', models.CharField(max_length=255)),
                ('penyelenggara_wilayah', models.CharField(help_text='Unit Detail LPM penyelenggara', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Program Pembinaan',
                'ordering': ['-tanggal_pelaksanaan'],
            },
        ),
    ]
