# Generated by Django 6.0.2 on 2026-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_jadwalgotongroyong'),
    ]

    operations = [
        migrations.CreateModel(
            name='KegiatanLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('Sosial', 'Sosial'), ('Pemberdayaan', 'Pemberdayaan'), ('Pengawasan', 'Pengawasan'), ('Rapat', 'Rapat Pleno'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jumlah_peserta', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Direncanakan', 'Direncanakan'), ('Berjalan', 'Berjalan'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Direncanakan', max_length=50)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM penyelenggara, diisi otomatis dari backend', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kegiatan LPM',
                'verbose_name_plural': 'Kegiatan LPM',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='PengurusLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Wakil Ketua', 'Wakil Ketua'), ('Sekretaris', 'Sekretaris'), ('Bendahara', 'Bendahara'), ('Koordinator Bidang', 'Koordinator Bidang'), ('Anggota', 'Anggota')], max_length=100)),
                ('bidang', models.CharField(blank=True, help_text='Misal: Pemberdayaan, Sosial', max_length=255, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('periode', models.CharField(help_text='Misal: 2023 - 2026', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM, diisi otomatis dari backend', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pengurus LPM',
                'verbose_name_plural': 'Pengurus LPM',
                'ordering': ['jabatan', 'nama'],
            },
        ),
    ]
