# Generated by Django 6.0.2 on 2026-03-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_kegiatanlpm_penguruslpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nama_lengkap',
            field=models.CharField(blank=True, help_text='Nama lengkap operator/pengurus', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nomor_telepon',
            field=models.CharField(blank=True, help_text='Nomor HP/WhatsApp aktif', max_length=20, null=True),
        ),
    ]
