# Generated by Django 6.0.2 on 2026-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_nama_lengkap_customuser_nomor_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
