# Generated by Django 6.0.2 on 2026-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanmusrenbang',
            name='alamat_lengkap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
