# Generated by Django 6.0.2 on 2026-04-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usulanmusrenbang_alamat_lengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanKeuanganLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], max_length=50)),
                ('sumber_dana', models.CharField(choices=[('Dana Desa', 'Dana Desa'), ('Bantuan / Donasi', 'Bantuan / Donasi'), ('Swadaya Warga', 'Swadaya Warga'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file_bukti', models.FileField(blank=True, null=True, upload_to='keuangan_lpm/')),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catatan Keuangan LPM',
                'verbose_name_plural': 'Catatan Keuangan LPM',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='InventarisLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aset', models.CharField(max_length=255)),
                ('kode_aset', models.CharField(blank=True, max_length=50, null=True)),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=1)),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Rusak Ringan', 'Rusak Ringan'), ('Rusak Berat', 'Rusak Berat')], default='Baik', max_length=50)),
                ('sumber_perolehan', models.CharField(max_length=100)),
                ('tahun_perolehan', models.IntegerField()),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventaris LPM',
                'verbose_name_plural': 'Inventaris LPM',
                'ordering': ['nama_aset'],
            },
        ),
        migrations.CreateModel(
            name='KaderLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('rt_rw', models.CharField(max_length=50)),
                ('jabatan', models.CharField(default='Anggota Biasa', max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('keahlian', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Non Aktif', 'Non Aktif')], default='Aktif', max_length=50)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kader/Relawan LPM',
                'verbose_name_plural': 'Kader/Relawan LPM',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='LaporanDigitalLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laporan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('Laporan Keuangan', 'Laporan Keuangan'), ('Laporan Kegiatan', 'Laporan Kegiatan'), ('Laporan Inventaris', 'Laporan Inventaris'), ('Laporan Akhir Tahun', 'Laporan Akhir Tahun'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('file_laporan', models.FileField(upload_to='laporan_lpm/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal_laporan', models.DateField()),
                ('is_public', models.BooleanField(default=False, help_text='Apakah laporan ini bisa dilihat oleh publik/warga')),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laporan Digital LPM',
                'verbose_name_plural': 'Laporan Digital LPM',
                'ordering': ['-tanggal_laporan'],
            },
        ),
        migrations.CreateModel(
            name='GaleriProyekLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_foto', models.CharField(max_length=255)),
                ('file_foto', models.ImageField(upload_to='galeri_proyek_lpm/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri_tambahan', to='users.usulanmusrenbang')),
            ],
            options={
                'verbose_name': 'Galeri Proyek LPM',
                'verbose_name_plural': 'Galeri Proyek LPM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeminjamanAlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peminjam', models.CharField(max_length=255)),
                ('rt_rw', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_pinjam', models.DateField()),
                ('rencana_kembali', models.DateField()),
                ('tanggal_kembali_aktual', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_peminjaman', to='users.inventarislpm')),
            ],
            options={
                'verbose_name': 'Peminjaman Alat',
                'verbose_name_plural': 'Peminjaman Alat',
                'ordering': ['-tanggal_pinjam'],
            },
        ),
        migrations.CreateModel(
            name='PresensiKegiatanLPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_hadir', models.DateTimeField(auto_now_add=True)),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to='presensi_lpm/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('unit_lpm', models.CharField(help_text='Unit Detail LPM', max_length=255)),
                ('kader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_presensi', to='users.kaderlpm')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='users.jadwalgotongroyong')),
            ],
            options={
                'verbose_name': 'Presensi Kegiatan LPM',
                'verbose_name_plural': 'Presensi Kegiatan LPM',
                'ordering': ['-waktu_hadir'],
                'unique_together': {('kegiatan', 'kader')},
            },
        ),
    ]
