# Generated by Django 6.0.2 on 2026-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesetting',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='landingpagesetting',
            name='about_title',
            field=models.CharField(default='Sekilas Pandang', max_length=255),
        ),
    ]
