# Generated by Django 6.0.2 on 2026-04-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_is_verified_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SEKDES', 'Sekretaris Desa'), ('KAUR_PERENCANAAN', 'Kaur Perencanaan'), ('KAUR_TU', 'Kaur Tata Usaha'), ('KAUR_KEUANGAN', 'Kaur Keuangan'), ('KASI_PEMERINTAHAN', 'Kasi Pemerintahan'), ('KASI_KESEJAHTERAAN', 'Kasi Kesejahteraan'), ('KASI_PELAYANAN', 'Kasi Pelayanan'), ('KADUS', 'Kepala Dusun'), ('POSYANDU', 'Posyandu'), ('LPM', 'LPM'), ('RW', 'Rukun Warga'), ('RT', 'Rukun Tetangga (RT)'), ('KARANG_TARUNA', 'Karang Taruna'), ('BUMDES', 'Bumdes'), ('TP_PKK', 'TP-PKK'), ('PUSKESOS', 'Puskesos (Sosial)'), ('WARGA', 'Warga')], default='ADMIN', max_length=50),
        ),
    ]
