# Generated by Django 6.0.2 on 2026-04-20 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SEKDES', 'Sekretaris Desa'), ('KAUR_PERENCANAAN', 'Kaur Perencanaan'), ('KAUR_TU', 'Kaur Tata Usaha'), ('KAUR_KEUANGAN', 'Kaur Keuangan'), ('KASI_PEMERINTAHAN', 'Kasi Pemerintahan'), ('KASI_KESEJAHTERAAN', 'Kasi Kesejahteraan'), ('KASI_PELAYANAN', 'Kasi Pelayanan'), ('KADUS', 'Kepala Dusun'), ('POSYANDU', 'Posyandu'), ('LPM', 'LPM'), ('RW', 'Rukun Warga'), ('RT', 'Rukun Tetangga (RT)'), ('KARANG_TARUNA', 'Karang Taruna'), ('BUMDES', 'Bumdes'), ('TP_PKK', 'TP-PKK'), ('PUSKESOS', 'Puskesos (Sosial)'), ('OWNER_TOKO', 'Pemilik Toko (UMKM)'), ('WARGA', 'Warga')], default='ADMIN', max_length=50),
        ),
        migrations.CreateModel(
            name='UMKMShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toko UMKM',
                'verbose_name_plural': 'Toko UMKM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='umkm_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.umkmshop')),
            ],
            options={
                'verbose_name': 'Produk UMKM',
                'verbose_name_plural': 'Produk UMKM',
                'ordering': ['-created_at'],
            },
        ),
    ]
