# Generated by Django 6.0.2 on 2026-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_customuser_role_umkmshop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkmshop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Toko'),
        ),
        migrations.AddField(
            model_name='umkmshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='umkm_logos/', verbose_name='Logo Toko'),
        ),
        migrations.AddField(
            model_name='umkmshop',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 08123...', max_length=20, null=True, verbose_name='WhatsApp / No HP'),
        ),
        migrations.AlterField(
            model_name='umkmshop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Toko'),
        ),
        migrations.AlterField(
            model_name='umkmshop',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Terverifikasi'),
        ),
        migrations.AlterField(
            model_name='umkmshop',
            name='shop_name',
            field=models.CharField(max_length=255, verbose_name='Nama Toko'),
        ),
    ]
